### PR TITLE
Fix loading diffusers model (+support F64/I64 types)

### LINKED ISSUE #153: unsupported dtype 'F64'
Hi! Thanks for the great tool!

When I run sd.cpp with some not pruned SD models it drops the error.
```
[ERROR] model.cpp:773  - unsupported dtype 'F64'
```
It seems to me a simple thing to fix, either by supporting double float internally or converting during load into single float.
I want to hear you thoughts on this situation and how to solve it.

With best regards, AG

### PR DESCRIPTION
**Pull request by stduhpf**
Loading diffusers models wasn't working, this fixes it for me,. I also added support for SDXL diffusers model (the second text encoder wasn't being handled).

During testing, I came across models with 64bit types, so I added support for those too since they are supported by GGML. (Fixes https://github.com/leejet/stable-diffusion.cpp/issues/153, https://github.com/leejet/stable-diffusion.cpp/issues/669)

### CODE REVIEW

**Review by Green-Sky — APPROVED** [review]

File: model.cpp [hunk 1]
```diff
@@ -1071,7 +1106,10 @@ bool ModelLoader::init_from_safetensors_file(const std::string& file_path, const
             n_dims = 1;
         }
 
-        TensorStorage tensor_storage(prefix + name, type, ne, n_dims, file_index, ST_HEADER_SIZE_LEN + header_size_ + begin);
+        std::string new_name = prefix + name;
+        new_name             = convert_tensor_name(new_name);
+
+        TensorStorage tensor_storage(new_name, type, ne, n_dims, file_index, ST_HEADER_SIZE_LEN + header_size_ + begin);
```
Comment (stduhpf) [inline model.cpp]: This is breaking some LoRAs.

**Comment by leejet** [comment]
Thank you for your contribution.

**Comment by wbruna** [comment]
@stduhpf , I'm getting an 'f64 unsupported' error trying the model mentioned on #153 ( https://civitai.com/models/7371/rev-animated?modelVersionId=425083 , fp32 file):
```
./sd --model ./revAnimated_v2Rebirth.safetensors -p flower 
ggml_vulkan: Found 1 Vulkan devices:
ggml_vulkan: 0 = AMD Radeon RX 7600 XT (RADV NAVI33) (radv) | uma: 0 | fp16: 1 | warp size: 64 | shared memory: 65536 | int dot: 1 | matrix cores: KHR_coopmat
[INFO ] stable-diffusion.cpp:210  - loading model from './revAnimated_v2Rebirth.safetensors'
[INFO ] model.cpp:998  - load ./revAnimated_v2Rebirth.safetensors using safetensors format
[INFO ] stable-diffusion.cpp:259  - Version: SD 1.x 
[INFO ] stable-diffusion.cpp:292  - Weight type:                 f32
[INFO ] stable-diffusion.cpp:293  - Conditioner weight type:     f32
[INFO ] stable-diffusion.cpp:294  - Diffusion model weight type: f32
[INFO ] stable-diffusion.cpp:295  - VAE weight type:             f16
  |====================>                             | 459/1130 - 0.00it/sterminate called after throwing an instance of 'std::runtime_error'
  what():  type f64 unsupported for integer quantization: no dequantization available
Abortado (imagem do núcleo gravada)
```

This is on master-dafc32d .

**Comment by stduhpf** [comment]
Yeah, F64 is still not properly supported. I didn't realize there isn't a built in "dequantization" (or rather quantization in that case) function for F64 to F32 in GGML, so I just implemented it with https://github.com/leejet/stable-diffusion.cpp/pull/726. This fix the crash during loading time, but I can't get inference to run with either Vulkan or CPU backends when using the models with F64 weights. Forcing it to use F32 works with the new new changes I made ( `--type f32`).
