### PR TITLE
Fix Flux: clip_l support (SD3/3.5 improvements included)

### LINKED ISSUE #396: Bug: Clip-L does absolutely nothing with Flux models.
I was testing out alternative clip models for Flux (https://huggingface.co/zer0int/CLIP-GmP-ViT-L-14), and noticed the output were oddly similar to the ones I was getting with the original clip-l. 
Turns out the result are actually 100% identical (when using the same seed of course), not even a single bit of difference. Using the same models with ComfyUI does lead to noticably different outputs (with fixed seed).

|  | clip-L |  ViT-L-14 |
| - | - | - |
| Dev q3_k (sd.cpp) | test-dev-clip | test-dev-vit |
| Schnell q3_k  (sd.cpp) | test-schnell-clip | test-schnell-vit |
| Schnell fp8 (Comfyui) | ComfyUI_00515_ | ComfyUI_00514_ |
| Schnell q3_k (Comfyui) | ComfyUI_00517_ | ComfyUI_00516_ |

As a sidenote, this could explain why I was feeling like the generations I get with sdcpp look less detailed and more artifacty than when I'm using ComfyUI at the same quants.

### PR DESCRIPTION
**Pull request by stduhpf**
Fixes #396 

I made the clip backend skip the last text projection if the `text_projection` tensor doesn't exist This is mathematically equaivalent to replacing the `text_projection` with the identity matrix (aka `torch.eye()`).
Also replaced the matrix multiplication with a biasless linear layer when `text_projection` exists (somehow this changes the outcome).

### Flux.1 Schnell (q3_k): 
|  | clip-L |  ViT-L-14 |
| - | - | - |
| master | test-schnell-clip | test-schnell-vit |
| PR | test-schnell-clip | test-schnell-vit |

### SD3 2B (q8_0):
| Master | PR |
| - | - |
| sd3-master | output |

### SD3.5 Large Turbo (q4_1)

| Master | PR |
| - | - |
| output | output |

### CODE REVIEW

**Comment by stduhpf** [comment]
If anyone know how this is all supposed to work, feel free to improve the code.

**Comment by stduhpf** [comment]
Ok I believe i got it now

**Comment by stduhpf** [comment]
Hard-coding the prompt for clip to always be `"Painting, in the style of starry night by Van Gogh"`, while keeping the same example prompt for T5 (`"a lovely cat holding a sign says 'flux.cpp'"`) now gives this result: 
test
I'm 99.99% certain this PR is now ready for merge.

**Comment by stduhpf** [comment]
@leejet does this look good enough to merge?

File: conditioner.hpp [hunk 1]
```diff
@@ -1073,7 +1065,7 @@ struct FluxCLIPEmbedder : public Conditioner {
         return {{clip_l_tokens, clip_l_weights}, {t5_tokens, t5_weights}};
     }
 
-    SDCondition get_learned_condition_common(ggml_context* work_ctx,
+      SDCondition get_learned_condition_common(ggml_context* work_ctx,
```
Comment (Green-Sky) [inline conditioner.hpp:1068]: extra spaces?

File: clip.hpp [hunk 2]
```diff
@@ -711,7 +711,11 @@ class CLIPTextModel : public GGMLBlock {
         if (return_pooled) {
             auto text_projection = params["text_projection"];
             ggml_tensor* pooled  = ggml_view_1d(ctx, x, hidden_size, x->nb[1] * max_token_idx);
-            pooled               = ggml_mul_mat(ctx, ggml_cont(ctx, ggml_transpose(ctx, text_projection)), pooled);
+            if(text_projection != NULL){
```
Comment (Green-Sky) [inline clip.hpp:714]: try to fit in the formatting more with the surrounding. ( spaces )

**Comment by stduhpf** [comment]
Ok it works again now.

**Comment by leejet** [comment]
Thank you for your contribution
